spring:
  #  cache:
  #    type: redis
  #    host: localhost
  #    port: 6379
  #    redis:
  #      time-to-live: 60000

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bookingboo}
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

app:
  MPESA_SERVICE_URL: ${MPESA_SERVICE_URL:http://localhost:8011/sendStkPush}
  MPESA_SERVICE_URL_TRANSACTION: ${MPESA_SERVICE_URL:http://localhost:8011/getTransaction/}